/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/bed/model.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bed(props) {
   const { nodes, materials } = useGLTF("./models/bed/model.glb");
   return (
      <group {...props} dispose={null}>
         <mesh
            geometry={nodes.mesh_0.geometry}
            material={materials["carpetWhite(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_1.geometry}
            material={materials["custom22(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_2.geometry}
            material={materials["metal(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_3.geometry}
            material={materials["custom17(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_4.geometry}
            material={materials["brownLight(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_5.geometry}
            material={materials["purpleLight(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_6.geometry}
            material={materials["orange(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_7.geometry}
            material={materials["yellow(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_8.geometry}
            material={materials["green(Clone)"]}
         />
      </group>
   );
}

useGLTF.preload("/models/bed/model.glb");
