/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/boxes/model.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Boxes(props) {
   const { nodes, materials } = useGLTF("./models/boxes/model.glb");
   return (
      <group {...props} dispose={null}>
         <group position={[-0.413, -0.153, 0.1]}>
            <mesh
               geometry={nodes.mesh_0.geometry}
               material={materials["wood(Clone)"]}
            />
            <mesh
               geometry={nodes.mesh_0_1.geometry}
               material={materials["woodDark(Clone)"]}
            />
         </group>
         <group position={[-0.013, -0.153, 0]}>
            <mesh
               geometry={nodes.mesh_1.geometry}
               material={materials["woodDark(Clone)"]}
            />
            <mesh
               geometry={nodes.mesh_1_1.geometry}
               material={materials["wood(Clone)"]}
            />
            <mesh
               geometry={nodes.mesh_1_2.geometry}
               material={materials["rock(Clone)"]}
            />
         </group>
         <group position={[0.287, -0.153, 0]}>
            <mesh
               geometry={nodes.mesh_2.geometry}
               material={materials["wood(Clone)"]}
            />
            <mesh
               geometry={nodes.mesh_2_1.geometry}
               material={materials["rock(Clone)"]}
            />
         </group>
      </group>
   );
}

useGLTF.preload("./models/boxes/model.glb");
