/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/carpet/model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Carpet(props) {
  const { nodes, materials } = useGLTF('./models/carpet/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials['custom19(Clone)']} />
      <mesh geometry={nodes.mesh_0_1.geometry} material={materials['custom18(Clone)']} />
    </group>
  )
}

useGLTF.preload('./models/carpet/model.glb')
