/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/chair/model.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Chair(props) {
   const { nodes, materials } = useGLTF("./models/chair/model.glb");
   
   return (
      <group {...props} dispose={null}>
         <mesh
            geometry={nodes["mergedBlocks(Clone)"].geometry}
            material={materials["custom22(Clone)"]}
         />
      </group>
   );
}

useGLTF.preload("./models/chair/model.glb");
