/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/fan/model.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Fan(props) {
   const { nodes, materials } = useGLTF("./models/fan/model.glb");
   return (
      <group {...props} dispose={null}>
         <mesh
            geometry={nodes.mesh_0.geometry}
            material={materials["custom49(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_1.geometry}
            material={materials["_defaultMat(Clone)(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_2.geometry}
            material={materials["dark(Clone)(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_3.geometry}
            material={materials["metalLight(Clone)(Clone)"]}
         />
      </group>
   );
}

useGLTF.preload("./models/fan/model.glb");
