/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/floor/model.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Floor(props) {
   const { nodes, materials } = useGLTF("./models/floor/model.glb");
   return (
      <group {...props} dispose={null}>
         <mesh
            geometry={nodes.mesh_0.geometry}
            material={materials["wood(Clone)"]}
         />
         <mesh
            geometry={nodes.mesh_0_1.geometry}
            material={materials["woodDark(Clone)"]}
         />
      </group>
   );
}

useGLTF.preload("./models/floor/model.glb");
